name: Build

on:
  push:
    branches: [master]
    paths:
      - "**.ts"
      - "**.json"
      - "**.yml"
  pull_request:
    branches: [master]
    paths:
      - "**.ts"
      - "**.json"
      - "**.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install --no-verify

      - name: Check formatting
        run: bun fix

      - name: Test
        run: bun test

      - name: Build
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: page
          build_dir: dist
          fqdn: https://t.himeno-sena.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: sena-tab-extension
          path: extension/
